import os
import sys
from cryptography.fernet import Fernet

# --- Security: Decryption Logic ---

# 1. Fetch the Key from Environment
# You must set 'APP_ENCRYPTION_KEY' in your OS or IDE environment variables.
encryption_key = os.environ.get('APP_ENCRYPTION_KEY')

if not encryption_key:
    # Fallback for development ONLY (Remove in production!)
    print("WARNING: No APP_ENCRYPTION_KEY found. App may fail to decrypt passwords.")
    # You can paste the key generated by setup_encryption.py here for local testing:
    encryption_key = b'JpcFxegplVxIMNAD0eq1u3IMqWbokaruBDxBQzNiVaI=' 

def decrypt_secret(encrypted_val):
    """Decrypts a string using the environment key."""
    if not encrypted_val or not encryption_key:
        return None
    try:
        cipher_suite = Fernet(encryption_key)
        return cipher_suite.decrypt(encrypted_val.encode()).decode()
    except Exception as e:
        print(f"CRITICAL: Password decryption failed. Check your Key. Error: {e}")
        return None

# --- Encrypted Credentials ---
# PASTE the output from setup_encryption.py here:
ENC_DB_PASSWORD = 'gAAAAABpHpmP7tzldI4n4kyxBm5sFUdNOR_cbP7AKUy3zp1BtcK4pT0vbWmxtXctydk9y6oOnl88j-zMT5wTMDDrn8q_3Cyi3g=='
ENC_EMAIL_PASSWORD = 'gAAAAABpHpmP1vvyqqwGcupd7wDgkLhakNPDILMuxHxKJ6qBtbPcnYH5lyr2dbZuNLs1l1jt04vZk_zeL3dr-HBc1JtbgjPIzQ=='


# --- App Configuration ---

DB_CONFIG = {
    'host': 'localhost',
    'user': 'root',
    # Decrypts the password at the moment of access
    'password': decrypt_secret(ENC_DB_PASSWORD),
    'database': 'icscv'
}

# Email Configuration
MAIL_SERVER = os.environ.get('MAIL_SERVER', 'smtp.gmail.com')
MAIL_PORT = int(os.environ.get('MAIL_PORT', 587))
MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() == 'true'
MAIL_USERNAME = os.environ.get('MAIL_USERNAME', 'panachorallc@gmail.com')
MAIL_PASSWORD = decrypt_secret(ENC_EMAIL_PASSWORD)
MAIL_DEFAULT_SENDER = os.environ.get('MAIL_DEFAULT_SENDER', 'noreply@carrierverify.com')
MAIL_ADMIN_RECEIVER = os.environ.get('MAIL_ADMIN_RECEIVER', 'tosinajy@gmail.com')