import os
import sys
from cryptography.fernet import Fernet

# --- Security: Decryption Logic ---

# 1. Fetch the Key from Environment
# You must set 'APP_ENCRYPTION_KEY' in your OS or IDE environment variables.
encryption_key = os.environ.get('APP_ENCRYPTION_KEY')

if not encryption_key:
    # Fallback for development ONLY (Remove in production!)
    print("WARNING: No APP_ENCRYPTION_KEY found. App may fail to decrypt passwords.")
    # You can paste the key generated by setup_encryption.py here for local testing:
    encryption_key = b'Vui9_XcG1WaDlEz4Z4eVjBnq6-ZIacmVF9N2ml9QhN8=' 

def decrypt_secret(encrypted_val):
    """Decrypts a string using the environment key."""
    if not encrypted_val or not encryption_key:
        return None
    try:
        cipher_suite = Fernet(encryption_key)
        return cipher_suite.decrypt(encrypted_val.encode()).decode()
    except Exception as e:
        print(f"CRITICAL: Password decryption failed. Check your Key. Error: {e}")
        return None

# --- Encrypted Credentials ---
# PASTE the output from setup_encryption.py here:
ENC_DB_PASSWORD = 'gAAAAABpIES1pkHstbMi3ibP7BwZ_lJYs_ypZi8Y3mT_UaJH3dSHZVK2bkN5qv4uVniv0B7kl6QrhG12yhp9FzSPriyMdE1fzA=='
ENC_EMAIL_PASSWORD = 'gAAAAABpIES1hN2hj3izcqpI0hZsEvJ0SN5TS8I88bgEWuYmdnxeRFnI36ryTixQX4VNfoNELaeeC7OxniNfhzCGmIGCgEHZuQ=='


# --- App Configuration ---

DB_CONFIG = {
    'host': 'localhost',
    'user': 'root',
    # Decrypts the password at the moment of access
    'password': 'vaug', # decrypt_secret(ENC_DB_PASSWORD),
    'database': 'ccv'
}

# Email Configuration
MAIL_SERVER = os.environ.get('MAIL_SERVER', 'smtp.gmail.com')
MAIL_PORT = int(os.environ.get('MAIL_PORT', 587))
MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() == 'true'
MAIL_USERNAME = os.environ.get('MAIL_USERNAME', 'panachorallc@gmail.com')
MAIL_PASSWORD = decrypt_secret(ENC_EMAIL_PASSWORD)
MAIL_DEFAULT_SENDER = os.environ.get('MAIL_DEFAULT_SENDER', 'noreply@carrierverify.com')
MAIL_ADMIN_RECEIVER = os.environ.get('MAIL_ADMIN_RECEIVER', 'tosinajy@gmail.com')